import localFont from "next/font/local";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
 
import {Open_Sans  } from "next/font/google";

const openSans= Open_Sans({
  subsets:['latin'],
  weight:['500','600','700','800']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} antialiased`}
      >
        <NextTopLoader height={4} showSpinner={false} color={"#f49e0b"} />
        {children}
      </body>
    </html>
  );
}
